config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :brands
  resources :categories
  resources :searches
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'carts/show'
  resources :products
  resources :cart_items
  resource  :carts, only:[:show]
  root 'products#index'
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions"}
  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions"}
  # eg. http://localhost:3000/admins/sign_in
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
        user ||= User.new
        can :read, Product
    
        if user.present?  # additional permissions for logged in users 
          can :read, Product
          can :manage, Search
          can :manage, Cart, user_id: user.id         
          # can :read, Cart
          # can :update, Cart
    
          if user.admin?  # additional permissions for administrators
            can :manage, Product
          end
        end
      end
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
 

app/models/admin.rb
class Admin < ApplicationRecord
  def admin?
    true
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/brand.rb
class Brand < ApplicationRecord
  belongs_to :category
  has_many :product
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items
    has_many :orders
    before_save :set_subtotal
    




    def subtotal
        cart_items.collect{|cart_item| cart_item.valid? ? cart_item.unit_price*cart_item.quantity : 0}.sum
    end



    private

    def set_subtotal
        self[:subtotal] = subtotal
    end







end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :cart
    belongs_to :product



    before_save :set_unit_price
    before_save :set_total

    def unit_price
        if persisted?
            self[:unit_price]
        else
            product.price
        end
    end


    def total
        unit_price*quantity
    end


    private

    def set_unit_price
        self[:unit_price] = unit_price 
    end

    def set_total
        self[:total] = total * quantity
    end




end

app/models/category.rb
class Category < ApplicationRecord
    has_many :brands
    has_many :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :cart
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category
    belongs_to :brand
    belongs_to :store
    has_many :cart_items
    has_one_attached :image
    

    def self.search(search)
        if search
            where(['title LIKE ? OR description LIKE ?', "%#{search}%", "%#{search}%"])
        else
            all
        end
    end
end

app/models/search.rb
class Search < ApplicationRecord
    def products
        @products ||= find_products
    end


    def find_products
        products = Product.order(:title)
        products = Product.where("title LIKE ?", "%#{keywords}%") if keywords.present?
        products = Product.where(category_id: category_id) if category_id.present?
        products = Product.where(brand_id: brand_id) if brand_id.present?
        products = Product.where(price: price) if price.present?
        products
    end

end

app/models/store.rb
class Store < ApplicationRecord
    has_many :product
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  

  def admin?
    false
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>E-commerce</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-inverse bg-light border border-primary">
  <a class="navbar-brand btn btn-outline-info font-weight-bold" href="/">E-commerce</a>
  
  <form class="form-inline">
  <%= form_tag(products_path, :method => "get", id: "search-form", html: {class: 'form-group'}) do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search products by title, description",
     class: "form-control", style: "width:280px !important;" %>
    <%= submit_tag "Search", :class => 'btn btn-info m-2 font-weight-bold',:name => nil%>
    <%if user_signed_in?%>
      <%= link_to "Filter By", new_search_path , :class => 'btn btn-info m-2 font-weight-bold' %>
    <% end %>
  <% end %>
  </form>
  <% if current_user %>
  <div id="cart" class='btn btn-warning font-weight-bold'>
    <%= render 'carts/cart'%>
  </div>
  <% else %>
  <%= link_to "Cart", new_user_registration_path , 
  :class => 'btn btn-warning m-2 font-weight-bold' %>
  <% end %>
    <div style="padding-left: 10px;">
    <% if current_user %>
      <button class="btn btn-outline-danger font-weight-bold" type="button">
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete %></button>

    <% else %>

      <button class="btn btn-outline-success font-weight-bold" type="button">
      <%= link_to 'Sign up', new_user_registration_path %></button>
      <button class="btn btn-outline-success font-weight-bold" type="button">
      <%= link_to 'Sign in', new_user_session_path %></button>
    <% end %>
      
    </div>
    
</nav>

    <%= yield %>
 
  </body>
</html>