config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :brands
  resources :categories
  resources :searches
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'carts/show'
  resources :products
  resources :cart_items
  resource  :carts, only:[:show]
  root 'products#index'
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions"}
  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions"}
  # eg. http://localhost:3000/admins/sign_in
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
        user ||= User.new
        can :read, Product
    
        if user.present?  # additional permissions for logged in users 
          can :read, Product
          can :manage, Search
          can :manage, Cart, user_id: user.id         
          # can :read, Cart
          # can :update, Cart
    
          if user.admin?  # additional permissions for administrators
            can :manage, Product
          end
        end
      end
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
 

app/models/admin.rb
class Admin < ApplicationRecord
  def admin?
    true
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  belongs_to :category
  has_many :product
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items
    has_many :orders
    before_save :set_subtotal
    




    def subtotal
        cart_items.collect{|cart_item| cart_item.valid? ? cart_item.unit_price*cart_item.quantity : 0}.sum
    end



    private

    def set_subtotal
        self[:subtotal] = subtotal
    end







end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :cart
    belongs_to :product



    before_save :set_unit_price
    before_save :set_total

    def unit_price
        if persisted?
            self[:unit_price]
        else
            product.price
        end
    end


    def total
        unit_price*quantity
    end


    private

    def set_unit_price
        self[:unit_price] = unit_price 
    end

    def set_total
        self[:total] = total * quantity
    end




end

app/models/category.rb
class Category < ApplicationRecord
    has_many :brands
    has_many :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :cart
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category
    belongs_to :brand
    belongs_to :store
    has_many :cart_items
    has_one_attached :image
    

    def self.search(search)
        if search
            where(['title LIKE ? OR description LIKE ?', "%#{search}%", "%#{search}%"])
        else
            all
        end
    end
end

app/models/search.rb
class Search < ApplicationRecord
    def products
        @products ||= find_products
    end


    def find_products
        products = Product.order(:title)
        products = Product.where("title LIKE ?", "%#{keywords}%") if keywords.present?
        products = Product.where(category_id: category_id) if category_id.present?
        products = Product.where(brand_id: brand_id) if brand_id.present?
        products = Product.where(price: price) if price.present?
        products
    end

end

app/models/store.rb
class Store < ApplicationRecord
    has_many :product
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders
  

  def admin?
    false
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/brands_controller.rb
class BrandsController < InheritedResources::Base

  private

    def brand_params
      params.require(:brand).permit(:name, :category_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper



    def current_cart
        if !session[:cart_id].nil?
            Cart.find(session[:cart_id])
        else
            Cart.new
        end
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/brands/_form.html.erb
<%= form_with(model: brand, local: true) do |form| %>
  <% if brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
        <% brand.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :category_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing Brand</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Brands</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.name %></td>
        <td><%= brand.category.name %></td>
        <td><%= link_to 'Show', brand %></td>
        <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
        <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brand', new_brand_path %>

app/views/brands/new.html.erb
<h1>New Brand</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @brand.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @brand.category_id %>
</p>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>